version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    target_branch: 'dependabot'
    allowed_updates:
      - match:
          update_type: 'all'
    version_requirement_updates: 'increase_versions'
